DECLARE @Vendor_ID VARCHAR(10) = 'VND123';
DECLARE @Item_Desc VARCHAR(50) = '%ITEM NAME%'
;

WITH RANKS AS (
    SELECT ITMID, PRDCTG,
        RANK() OVER(PARTITION BY PRDCTG ORDER BY ITMID) AS RANK_NUM
    FROM DCSCIM
    WHERE VNDID = @Vendor_ID AND ITMDESC LIKE @Item_Desc
    GROUP BY ITMID, PRDCTG
),
RANK_1 AS (
    SELECT *
    FROM RANKS
    WHERE RANK_NUM = 1
),
COUNTS AS (
    SELECT TOP 1 COUNT(*) COUNTS, PRDCTG
    FROM DCSCIM
    WHERE VNDID = @Vendor_ID AND ITMDESC LIKE @Item_Desc
    GROUP BY PRDCTG
    ORDER BY COUNTS DESC
),
FINAL AS (
    SELECT ITMID, C.PRDCTG, COUNTS
    FROM COUNTS C
    INNER JOIN RANK_1 R ON C.PRDCTG = R.PRDCTG
)
SELECT *
FROM FINAL
;
